### ISSUE TITLE
Eai Mateus, gostaria de tirar uma duvida com vc se possivel

### ISSUE THREAD

**Issue by matheus-kirchesch-old** [Mateuus/src#1]

**Comment by Mateuus** [comment]
Pode falar

**Comment by matheus-kirchesch-old** [comment]
Caramba, foi rapido, vc sabe do que eu preciso pra compilar esse projeto? tipo algumas instruções basicas algo do tipo? como vc aprendeu?

**Comment by Mateuus** [comment]
Visual Studio 2008 R2 esse projeto é muito antigo. 

https://forum.ragezone.com/f791/
Nesse forum tem algumas informações.


Faz tanto tempo que eu não lembro

**Comment by matheus-kirchesch-old** [comment]
kk dmr, valew, vou baixar o vs 2008, no caso seria o mesmo pro warz? https://github.com/Mateuus/UndeadAlpha

vou dar uma lida
